
# This file was *autogenerated* from the file hypercube.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_4 = Integer(4)
from itertools import combinations

# On explore l'hypercube de facon brute

k = _sage_const_4 
l = _sage_const_2 **(k-_sage_const_1 ) + _sage_const_1  
g = graphs.CubeGraph(k)
it = combinations(g.vertices(), l) 

g2 = Graph()

while not g2.is_tree():
    # try except ?
    g2 = g.subgraph(vertices=next(it))

print('Vertices : ')
print(g2.vertices())
print('Edges : ')
print(g2.edges(labels=False))
g2.show()

