
# This file was *autogenerated* from the file hypercube_backtracking.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_4 = Integer(4)
from itertools import combinations

# On explore l'hypercube de facon brute

k = _sage_const_4 
l = _sage_const_2 **(k-_sage_const_1 ) + _sage_const_1  
g = graphs.CubeGraph(k)

vertices = g.vertices()
selected = []

g2 = Graph()

g2 = g.subgraph(vertices=vertices)

print('Vertices : ')
print(g2.vertices())
print('Edges : ')
print(g2.edges(labels=False))
g2.show()

