
# This file was *autogenerated* from the file plntest.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_5 = Integer(5); _sage_const_4 = Integer(4)# programme lineaire sage

# arbre a n sommets

n = _sage_const_5  # taille de l'arbre
k = _sage_const_4  # taille du sous-arbre
a = _sage_const_4  # nombre d'arete

p = MixedIntegerLinearProgram()

# aretes, sommets et feuilles
x = p.new_variable(binary = True)
y = p.new_variable(binary = True)
f = p.new_variable(integer = True, nonnegative = False)

# objectif
p.set_objective(p.sum(f[i] for i in range(n)) + p.sum(x[i,j] for i in range(n) for j in range(n)) )

# contraintes
p.add_constraint(p.sum(y[i] for i in range(n)) == k)  # k la taille du sous arbre 

# contraintes aretes (a generer)
p.add_constraint(x[_sage_const_0 ,_sage_const_1 ] <= (y[_sage_const_0 ] + y[_sage_const_1 ])/_sage_const_2 )  # presence d'une arete
p.add_constraint(x[_sage_const_1 ,_sage_const_2 ] <= (y[_sage_const_1 ] + y[_sage_const_2 ])/_sage_const_2 )  # on decrit chaque arete a la main
p.add_constraint(x[_sage_const_1 ,_sage_const_3 ] <= (y[_sage_const_1 ] + y[_sage_const_3 ])/_sage_const_2 )  # necessite (i,j)
p.add_constraint(x[_sage_const_3 ,_sage_const_4 ] <= (y[_sage_const_3 ] + y[_sage_const_4 ])/_sage_const_2 )  
p.add_constraint(x[_sage_const_4 ,_sage_const_3 ] <= (y[_sage_const_3 ] + y[_sage_const_4 ])/_sage_const_2 )  # le symetrique ?

p.add_constraint(p.sum(y[i] for i in range(n)) == p.sum(x[i,j] for i in range(n) for j in range(n)) + _sage_const_1 )  # arbre, connexe

for i in range(n):
        p.add_constraint(f[i] <= _sage_const_2  - (p.sum(x[i,j] for j in range(n))) )  # contraintes sur les feuilles
        p.add_constraint(f[i] <= _sage_const_1  + (p.sum(x[i,j] for j in range(n))) )  # necessite d'associer aretes et sommets
        p.add_constraint(f[i] <= y[i]) # une feuille est un sommet 
        # contraintes utiles ou redondantes ?
        p.add_constraint(x[i,i] == _sage_const_0 ) # pas d'arete vers sois-meme

# resolution
print("Solve")
print(p.solve())
print("Aretes x")
print(p.get_values(x))
print("Sommets y")
print(p.get_values(y))
print("Feuilles f")
print(p.get_values(f))

